version: '2'
services:
    jworkzone-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/jworkzone/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=jworkzone
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
